-- Semilla de datos para daily_quotes (Extendido)
-- Inserta frases para hoy y los próximos 45 días

insert into public.daily_quotes (quote, author, date, category)
values
  ('La única forma de hacer un gran trabajo es amar lo que haces.', 'Steve Jobs', CURRENT_DATE, 'Inspiración'),
  ('El éxito es la suma de pequeños esfuerzos repetidos día tras día.', 'Robert Collier', CURRENT_DATE + 1, 'Motivación'),
  ('Cree que puedes y ya estarás a medio camino.', 'Theodore Roosevelt', CURRENT_DATE + 2, 'Fe'),
  ('No cuentes los días, haz que los días cuenten.', 'Muhammad Ali', CURRENT_DATE + 3, 'Acción'),
  ('La vida es 10% lo que te ocurre y 90% cómo reaccionas a ello.', 'Charles R. Swindoll', CURRENT_DATE + 4, 'Actitud'),
  ('Lo que no te mata te hace más fuerte.', 'Friedrich Nietzsche', CURRENT_DATE + 5, 'Resiliencia'),
  ('La felicidad no es algo hecho. Proviene de tus propias acciones.', 'Dalai Lama', CURRENT_DATE + 6, 'Felicidad'),
  ('Si puedes soñarlo, puedes hacerlo.', 'Walt Disney', CURRENT_DATE + 7, 'Sueños'),
  ('El único modo de hacer un gran trabajo es amar lo que haces.', 'Steve Jobs', CURRENT_DATE + 8, 'Pasión'),
  ('La creatividad es la inteligencia divirtiéndose.', 'Albert Einstein', CURRENT_DATE + 9, 'Creatividad'),
  ('No busques los errores, busca un remedio.', 'Henry Ford', CURRENT_DATE + 10, 'Soluciones'),
  ('La vida es lo que pasa mientras estás ocupado haciendo otros planes.', 'John Lennon', CURRENT_DATE + 11, 'Vida'),
  ('El futuro pertenece a quienes creen en la belleza de sus sueños.', 'Eleanor Roosevelt', CURRENT_DATE + 12, 'Futuro'),
  ('No hay caminos para la paz; la paz es el camino.', 'Mahatma Gandhi', CURRENT_DATE + 13, 'Paz'),
  ('A veces ganas, a veces aprendes.', 'John Maxwell', CURRENT_DATE + 14, 'Aprendizaje'),
  ('La mejor venganza es el éxito masivo.', 'Frank Sinatra', CURRENT_DATE + 15, 'Éxito'),
  ('No dejes para mañana lo que puedas hacer hoy.', 'Benjamin Franklin', CURRENT_DATE + 16, 'Productividad'),
  ('La simplicidad es la máxima sofisticación.', 'Leonardo da Vinci', CURRENT_DATE + 17, 'Simplicidad'),
  ('Sé el cambio que quieres ver en el mundo.', 'Mahatma Gandhi', CURRENT_DATE + 18, 'Cambio'),
  ('Todo parece imposible hasta que se hace.', 'Nelson Mandela', CURRENT_DATE + 19, 'Persistencia'),
  ('La educación es el arma más poderosa que puedes usar para cambiar el mundo.', 'Nelson Mandela', CURRENT_DATE + 20, 'Educación'),
  ('No llores porque ya se terminó, sonríe porque sucedió.', 'Dr. Seuss', CURRENT_DATE + 21, 'Gratitud'),
  ('El fracaso es el condimento que da sabor al éxito.', 'Truman Capote', CURRENT_DATE + 22, 'Éxito'),
  ('La vida es un 10% lo que me ocurre y un 90% cómo reacciono a ello.', 'Charles Swindoll', CURRENT_DATE + 23, 'Actitud'),
  ('La mejor forma de predecir el futuro es crearlo.', 'Peter Drucker', CURRENT_DATE + 24, 'Innovación'),
  ('El conocimiento habla, pero la sabiduría escucha.', 'Jimi Hendrix', CURRENT_DATE + 25, 'Sabiduría'),
  ('La vida es una aventura atrevida o no es nada.', 'Helen Keller', CURRENT_DATE + 26, 'Aventura'),
  ('El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.', 'Albert Schweitzer', CURRENT_DATE + 27, 'Felicidad'),
  ('No he fallado. He encontrado 10.000 formas que no funcionan.', 'Thomas Edison', CURRENT_DATE + 28, 'Perseverancia'),
  ('La lógica te llevará de la A a la Z; la imaginación te llevará a todas partes.', 'Albert Einstein', CURRENT_DATE + 29, 'Imaginación'),
  ('La vida es muy simple, pero insistimos en hacerla complicada.', 'Confucio', CURRENT_DATE + 30, 'Simplicidad'),
  ('Lo que plantamos en el suelo de la contemplación, cosecharemos en la cosecha de la acción.', 'Meister Eckhart', CURRENT_DATE + 31, 'Reflexión'),
  ('La única verdadera sabiduría es saber que no sabes nada.', 'Sócrates', CURRENT_DATE + 32, 'Sabiduría'),
  ('El viaje de mil millas comienza con un solo paso.', 'Lao-Tse', CURRENT_DATE + 33, 'Inicio'),
  ('La mejor preparación para mañana es hacer lo mejor posible hoy.', 'H. Jackson Brown, Jr.', CURRENT_DATE + 34, 'Preparación'),
  ('La felicidad de tu vida depende de la calidad de tus pensamientos.', 'Marco Aurelio', CURRENT_DATE + 35, 'Pensamiento'),
  ('No hay sustituto para el trabajo duro.', 'Thomas Edison', CURRENT_DATE + 36, 'Esfuerzo'),
  ('Cáete siete veces, levántate ocho.', 'Proverbio japonés', CURRENT_DATE + 37, 'Resiliencia'),
  ('El éxito suele llegar a quienes están demasiado ocupados para buscarlo.', 'Henry David Thoreau', CURRENT_DATE + 38, 'Trabajo'),
  ('La vida se encoge o se expande en proporción al coraje de uno.', 'Anaïs Nin', CURRENT_DATE + 39, 'Valor'),
  ('No cuentes los días, haz que los días cuenten.', 'Muhammad Ali', CURRENT_DATE + 40, 'Acción'),
  ('La mente es todo. Lo que piensas, te conviertes.', 'Buda', CURRENT_DATE + 41, 'Mentalidad'),
  ('El momento es ahora.', 'Anónimo', CURRENT_DATE + 42, 'Presente'),
  ('Haz lo que puedas, con lo que tengas, donde estés.', 'Theodore Roosevelt', CURRENT_DATE + 43, 'Acción'),
  ('La vida es corta, sonríele a quien llora, ignora a quien te critica y sé feliz con quien te importa.', 'Anónimo', CURRENT_DATE + 44, 'Vida')
on conflict (date) do update 
set quote = excluded.quote, author = excluded.author, category = excluded.category;
